test: 
	echo "---------------Format errors----------------"
	echo ""


	echo "---------------header-problems--------------\n"
	echo ""
	../bsq Format_error/header_problem/*


	echo "---lines-problems : too long/short----------"
	echo ""
	../bsq Format_error/lines_problems/line_long_short/*


	echo "---lines-problems : lines count not equals header----------"
	echo ""
	../bsq Format_error/lines_problems/lines_count_not_equal_header/*


	echo "---lines-problems : wrong charset----------"
	echo ""
	../bsq Format_error/lines_problems/wrong_char/*